### ISSUE TITLE
Change or delete an object?

### ISSUE THREAD

**Issue by daviddelmonte** [ottersoftware/CoreDataStackSetup#4]
Thanks very much for this. Could you please explain how to activate change and delete?

**Comment by ottersoftware** [comment]
Hi David and apologies for the delay in responding.

I'm not 100% clear about what you are asking so some general thoughts and please feel free to add a comment if I've missed what you mean.

For the overall structure I'd suggest that you do something like the following...

1. The saveManagedObjectContext is used purely for saving.

2. The mainThreadManagedObjectContext is used for everything related to user interaction such as displaying data to the user, editing done by the user, etc.

3. Create child contexts of the mainThreadManagedObjectContext each time you want to import data, delete a lot of data, etc. Really anything which is time consuming should be done off the main thread.

4. Once you have run batch processes on a child context you can simply save them. The main thread context should pick up the fact that the child context has changed from the save. You might have to refresh the UI but the actual managed objects should already be in the mainThreadManagedObjectContext.
